name: Unit Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      = name: Deploy
        run: yarn deploy
      # - name: deploy file to server
      #   uses: wlixcc/SFTP-Deploy-Action@v1.0
      #   with:
      #     username: 'root' #ssh user name
      #     port: '2017' # 远程服务器ssh端口，默认22
      #     server: '10....' # 远程服务器IP
      #     ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # 认证服务器秘钥对的私钥
      #     local_path: 'dist/*' # 对应我们项目打包后的静态文件路径
      #     remote_path: '/home/...' # 服务器上的路径
